arch:
  - amd64

matrix:
  include:
    - language: go
      os: windows
      before_install:
        - go version
      install:
      before_script:
      script:
        - FILE_NAME=ElrondTestApp_TEST.exe
        - cd ./testApp/cmd/testApp
        - GO111MODULE=on go build -o $FILE_NAME .
        - ls
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN_SECONDARY
        file: $TRAVIS_BUILD_DIR/testApp/cmd/testApp/$FILE_NAME
        skip_cleanup: true
        draft: true
        on:
          branch: fix-windows

